CREATE DATABASE IF NOT EXISTS mini_groupware
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_general_ci;

USE mini_groupware;

CREATE TABLE IF NOT EXISTS team (
    team_id BIGINT NOT NULL AUTO_INCREMENT,
    team_name VARCHAR(100) NOT NULL,
    team_desc VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (team_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
